name: Tests

on:
  push:
    branches:
      - main
  pull_request: {}
  schedule:
    - cron: '0 23 * * SUN-THU'
  workflow_dispatch:

jobs:
  tests:
    if: (github.event_name == 'schedule' && github.repository == 'optuna/optuna-integration') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get -y install libopenblas-dev

    - name: Install
      run: |
        python -m pip install --upgrade pip

        # Install distributed to run importance_tests/test_init tests.
        # TODO(nabenabe0928/2024/03/12): Remove this version constraint once the following PR is merged.
        # https://github.com/dask/distributed/pull/8575
        # NOTE(nabenabe0928): dask-expr supports only python>=3.9.
        pip install --progress-bar off "distributed<2024.3.0"

        # NOTE(nabenabe0928): Got "AttributeError: module 'tensorflow' has no attribute 'estimator'".
        pip install "tensorflow<2.16.1"

        pip install --progress-bar off .[test]
        pip install --progress-bar off .[all]

        # TODO(not522): Remove the version constraint when splitting this workflow.
        # This constraint is necessary to use the old Pydantic.
        # See https://github.com/pydantic/pydantic/issues/5821.
        pip install --progress-bar off "typing_extensions<4.6.0"

        # Install optuna from optuna master
        pip install --progress-bar off git+https://github.com/optuna/optuna@master

    - name: Tests
      run: |
        pip install "numpy<1.24"
        pytest tests
